services:
  jenkins:
    build:
      context: ./
      dockerfile: Dockerfile
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkinspython
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

  firefox:
    image: selenium/standalone-firefox
    container_name: firefox
    ports:
      - "4444:4444"
    environment:
      - SE_OPTS=-port 4444


volumes:
  jenkins_home: